### ISSUE TITLE
Tela buga enter

### ISSUE THREAD

**Issue by otaciobarbosa** [GabrielLucasF/calculadora-javascript#1]
As vezes o input fica azul, bugando o ENTER que quando é apertado ele apaga as informacoes.

![WhatsApp Image 2022-11-21 at 15 28 37](https://user-images.githubusercontent.com/25693388/203132956-47e91424-3636-4035-93a3-54947b22001b.jpeg)

**Comment by GabrielLucasF** [comment]
Nesse caso foi porque dento do botão enter foi colocado a função do botão backspace sendo assim sempre que pressionava enter retornava o resultado apagando um numero da tela de conta.

antes:
```
else if(e.key == "Enter" || e.key == "NumEnter"){
        calcular();
        apaganumero();
}
```

corrigido:
```
else if(e.key == "Enter" || e.key == "NumEnter"){
        calcular();
}
```
