### ISSUE TITLE
3 Caclulos bugando a tela

### ISSUE THREAD

**Issue by otaciobarbosa** [GabrielLucasF/calculadora-javascript#2]
Quando faz mais de dois calculos o input retorna indefindo.

![image](https://user-images.githubusercontent.com/25693388/203133103-4199a6c4-dcc1-492f-94ac-9f9b7f353f25.png)

**Comment by GabrielLucasF** [comment]
O problema era que se não tivesse conta o resultado retornava "undefined" ´porém foi corrigido com uma condição.

antes:
`resultado.innerText = eval(res);`

agora:
```
if(res == ""){
        resultado.innerText = "0";
    }else{
        resultado.innerText = eval(res);
}
```

obs: sendo assim na situação do usuario pressionar enter sem digitar qualquer numero o resultado vai ser sempre 0
