### ISSUE TITLE
Não resolve o calculo

### ISSUE THREAD

**Issue by otaciobarbosa** [GabrielLucasF/calculadora-javascript#3]
Calculadora buga não retornando os resultados.

![image](https://user-images.githubusercontent.com/25693388/203133254-9d765cf9-64cc-4bc4-b0b5-f874fe6f5bbb.png)

**Comment by GabrielLucasF** [comment]
foi corrigido a linha de codigo onde o replace só mudava o primeiro "X" passado.

anterior:

```
if(res.indexOf("X") != -1){
     res = res.replace("X", "*");
}
```

corrigido:

```
if(res.indexOf("X") != -1){
     res = res.replaceAll("X", "*");
}
```

obs: usando o replaceAll todos os "X" idependente do tamanho da string será tranformado em "*"
